
# Epilogue: Choices (December 2017) #

The plane flies low to the east of Lisbon and turns over Costa Caparica for its final run into the airport. As I look out the window to the west I see Oeiras, Algés and Belém. The plane drops lower and I can make out the stadiums of Sporting Lisbon and Benfica, both of which have been graced by my presence. I glimpse the University of Lisbon’s, Faculdade de Letras, where I study Portuguese. Part of me feels very much like I’m coming home.

The last 10 days in London have been difficult. The city where I have lived for most of my life didn’t feel like home at all. Perhaps this was due to the sadness at saying goodbye to my daughter Maxime, as she flew out to work in Australia for a couple of years, or maybe it was an inevitable reaction to the excesses that surrounded London Decompression, but somehow it feels like more than that. On reflection the whole period back in the UK seemed uncomfortable.

One night in particular comes to mind. I have been visiting friends. In the early hours of the morning I leave their flat somewhat intoxicated. At first I think, as I walk through the deserted market, that maybe it’s because I’m not entirely sober, that everything seems strange. By the time I get to the cab office, I’m not so sure. I decide to continue walking along Markhouse Road. It seems like I’m in a parallel universe, a Waltenatestow as it were. Of course I haven’t been here for many months, or perhaps even a year, and so changes, like the new cycle path, are inevitable. But it’s not a change over time that is creating my mental dissonance, but rather changes between London and my new home. In contrast to Lisbon, the traffic seems so safe and orderly. At Lea Bridge Road I catch a 55 bus that announces the stops on the route home with the diction and efficiency of a dystopian future. My mind turns Bridget Jones on her head: “Does everything work in London?”. The city of my birth seems to have traded it’s charm for safety and efficiency.

My life in Lisbon, even if the tellings of my journey seem to suggest otherwise, is by and large solitary. While I get many invitations, I accept only a few and make fewer of my own. Spending time alone has led to sobriety, for alcohol and other narcotics, are the crutches that I have used to make my way around [l’enfer qu est les autres](https://en.wikipedia.org/wiki/No_Exit). I have no desire to drink when I’m on my own. My diet is healthy and balanced and largely devoid of animal products. I have been exercising too! When the aches and pains of my ageing body allow, I swim, walk, cycle, practice yoga and of course sail.

Most of my time is spent reading, writing (code and prose) and watching and listening to the outputs of, mostly English speaking, media. My Portuguese is coming along, but I am not yet a free reader, or listener. My speech is generally stilted, though I can make myself understood, and indeed, have had whole conversations with officialdom entirely in the [language of Camões](https://en.wikipedia.org/wiki/Lu%C3%ADs_de_Cam%C3%B5es).

The finishing of this tale as the year has come to a close has focussed my thinking on what to do next. I have known from when I started my journey that at this point I would have the enormous good fortune of three choices:

* Returning to the UK
* Staying in Portugal and trying to achieve Portuguese and therefore EU citizenship.
* Continuing to Travel with Kite
  
As a pre-teen, I remember going with my father and mother to buy a new car, a Simca 1300. There were three options in the showroom, all with metallic paint. One was dark green with brown seats, the other was gold with black seats and the final one was silver with red seats. The silver car stood head and shoulders above the rest. To me it conjured up images of an iconic 1960s Mercedes-Benz. It was a car of style and romance. My parents chose the green car. On reflection they had a thing for green. To sell their flat, multiple coats of paint were applied to cover the green walls and it is only in the last year or so that their green sofas have finally gone from my life.

Back in the early 1970’s their choice of a green car made me apoplectic with rage. How could they make such a stupid decision. I shouted, I cried, I stormed out of their house. Brexit conjures many of the same emotions for me as that Simca 1300 did back then, and, once again, I have shouted and cried, and this time, stormed out of the country on my boat. On course Brexit is a much bigger issue than a cheap french car, even if I still mourn the stylish automobile that could have ushered in my teenage years.

In the 1970s I think I probably stopped on the bridge that crosses the M1, as I often did after fits of rage, for all that lies ahead is Edgware, and no one really wants to run away to the end of the Northern Line. As my rage would subside then, perhaps my rage is subsiding now. Except now I’m not staring at Britain’s first motorway, but the river Tejo, and in front of me lies, not a London suburb with a Underground terminus, but the Atlantic and the rest of the world. Maybe I will return to the UK one day, but not yet. You may be buying that green car all over again but don’t expect me to be a passenger. Let’s just see how you do with your next model.

Through some miracle of technology, I have been able to listen to Test Match Special in the last few weeks. My mornings have been blessed with the gentle tones of [Aggers](https://en.wikipedia.org/wiki/Jonathan_Agnew) and [Tuffers](https://en.wikipedia.org/wiki/Phil_Tufnell) and the rest of the commentary team as they bring the current Ashes series to life. I even feel some love towards [Geoffrey Boycott](https://en.wikipedia.org/wiki/Geoffrey_Boycott) though I suspect that he and I would populate the opposite ends of most spectrums. Outputs of the British media such as the cricket commentary, Sherlock and Blue Planet II have made me nostalgic for my green and pleasant land. They have also made me aware of how much my personality has invested in the English language. It is the tongue in which I have expressed my thoughts for more than half a lifetime. I can learn all the Portuguese I want, but I fear I will never read [Cesário Verde](https://en.wikipedia.org/wiki/Ces%C3%A1rio_Verde) like I can [Oscar Wilde](https://en.wikipedia.org/wiki/Oscar_Wilde), [Florbela Espanca](https://en.wikipedia.org/wiki/Florbela_Espanca) like I can [Stevie Smith](https://en.wikipedia.org/wiki/Stevie_Smith) or [Fernando Pessoa](https://en.wikipedia.org/wiki/Fernando_Pessoa) like I can [W. H. Auden](https://en.wikipedia.org/wiki/W._H._Auden).

At the moment Kite is moored in Parque das Nações, literally the Park of Nations. My favourite way to get myself to the nearest metro station, Oriente, passes a white giraffe nestled amongst some date palms, encounters volcanos that can erupt with cascades of water and traverses a pedestrian crossing between the virtual and the real. “Variety is the spice of life” they say, so occasionally I will take an alternative route. One such takes me past all the flags of the world. I often linger awhile looking at the descriptions of the countries. The more I pass by here though, I realise, that right now, there is only one flag that even comes close to claiming my allegiance. It is pale blue with a white emblem consisting of a map of the world surrounded by two olive branches.

While seeking the nationality of another country may be expedient in these times, I am coming to find the whole idea of being associated with a single nation distasteful. Our notion of borders means that most of the wild creatures of the planet have more freedom of movement than we do as human beings. As the Syrian refugee crisis has shown, this is true even when our lives are in peril. Exchanging one nationality for another seems like drawing new cards in a rigged poker game, when really, we should be walking away from the table.

In practical terms, new nationality also takes time. In Portugal, which is fairly easy going, citizenship takes 5 years. If I wait that long I will be in my sixties. Hell I may even be dead. I will almost certainly have more frailties, all of which could act against further adventuring. Citizenship also requires residency and residency requires a physical address. A boat in a marina doesn’t count. Something that I discovered when I went to the town hall to register, as, in theory, I am required to by law, after three months in the Portugal. Despite my feelings about nationality, with all the uncertainty that is around at the moment, it would be foolish to rule out applying for another citizenship at some point, it’s just not a priority at the moment.

My brief brush with Portuguese immigration bureaucracy, did however, highlight to me something that, deep down, I have known all along. Living on a boat puts you in one of the interstices of our world, a zone where rules have hazy application. One of [Leonard Cohen’s cracks](https://www.goodreads.com/quotes/4484-there-is-a-crack-in-everything-that-s-how-the-light), where I feel, if I play my cards right, the light might come in. For the next three years I will probably be ok in Europe, and, if the worst comes to the worst, I may be able to continue to hang around after that, by carefully timed moves between [Schengen]https://en.wikipedia.org/wiki/Schengen_Area) and non-Schengen countries, though the non-Schengen countries are getting fewer and fewer. If Europe ultimately proves impossible, there is always the rest of the world. I can keep going as long as my physical strength holds out. Then, when the nursing home beckons, I can sail out into the ocean and disappear.

So my choice is made, I will continue travelling with Kite. In the spring I’ll probably head down to the Algarve and from there on into the mediterranean. There is much planning and preparation to do between now and then, oh, and I’ll need some more pens.
